import {createRequire} from 'node:module'; import fs from 'node:fs/promises'; import assert from 'node:assert/strict';
const require=createRequire('/home/autobyteus/workspace/.codex/worktrees/flat-agent-organization-model/autobyteus-web/package.json');
const {chromium}=require('playwright-core');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox'],headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});
const evidence={states:[],errors:[],assertions:[],limits:'Implementation fixture: actual Org context/index/facets and shared components, synthetic retained records. No provider, WebSocket, native shell or full API/E2E signoff.'};
page.on('pageerror',e=>evidence.errors.push(String(e)));
await page.route('**/graphql',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{agentDefinitions:[],runtimeCapabilities:[],agentTeams:[]}})}));
await page.route('**/references/**',route=>route.fulfill({status:200,contentType:'text/plain',headers:{'access-control-allow-origin':'*'},body:'Retained reference: exact report content.'}));
const snap=async(name)=>{
 await page.waitForTimeout(1000);
 await page.screenshot({path:`/tmp/aorg-ir040-render/${name}.png`,fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false,name+' page overflow');
 evidence.states.push({name,body:await page.locator('body').innerText(),overflow});
};
const expectOpen=async(test,open)=>assert.equal(await page.locator(`[data-test="${test}"]`).getAttribute('aria-expanded'),String(open));
const base='http://127.0.0.1:43140/ir040-compact-render?rootSubjectKind=agent_org&orgRunId=org-run&mode=active';
try{
 await page.goto(base,{waitUntil:'networkidle',timeout:120000});
 await page.locator('[data-test="team-delegated-tasks-section"]').waitFor({timeout:60000});
 await expectOpen('task-identity-toggle',false);
 assert.equal(await page.locator('[data-test="workspace-agent-orgs"] > div.uppercase').innerText(),'ORG');
 await snap('task-agent-compact-desktop');
 await page.locator('[data-test="team-delegated-task-summary-row"]').nth(1).click();
 await expectOpen('task-identity-toggle',false);
 assert.equal(await page.locator('[data-test="delegated-task-detail-pane"] nav').count(),0);
 await snap('task-team-compact-desktop');
 await page.locator('[data-test="task-direction-team"]').focus(); await page.keyboard.press('Enter');
 await expectOpen('task-identity-toggle',true);
 const details=page.locator('[data-test="task-identity-detail"]');
 assert.match(await details.innerText(),/agent-task-lead/);assert.match(await details.innerText(),/agent-task-worker/);
 assert.equal(await details.locator('[data-test="task-identity-agent"]').count(),3);
 await snap('task-team-identity-desktop');
 await page.locator('[data-test="team-delegated-task-lifecycle-row"]').first().click();
 await expectOpen('task-identity-toggle',false);
 assert.match(await page.locator('[data-test="delegated-task-item-direction"]').innerText(),/team\s*→\s*director/);
 await snap('reversed-submission-desktop');
 await page.locator('[data-test="team-delegated-task-reference-row"]').click();
 await page.locator('[data-test="delegated-task-reference-preview"]').waitFor();
 assert.equal(await page.locator('[data-test="task-identity-toggle"]').count(),0);
 await snap('reference-desktop');
 await page.locator('[data-test="collaboration-messages-header"]').click();
 await expectOpen('message-identity-toggle',false);
 assert.doesNotMatch(await page.locator('[data-test="team-communication-left-list"]').innerText(),/\/team\/lead|Task ·|agent-task-lead/);
 await snap('messages-compact-desktop');
 await page.locator('[data-test="message-identity-toggle"]').focus(); await page.keyboard.press('Space');
 await expectOpen('message-identity-toggle',true);
 assert.match(await page.locator('[data-test="message-identity-detail"]').innerText(),/agent-task-lead/);
 await snap('messages-identity-desktop');
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-test="narrow-panel"]').tap();
 await snap('messages-identity-narrow');
 await page.locator('[data-test="message-identity-toggle"]').tap();await expectOpen('message-identity-toggle',false);
 await snap('messages-compact-narrow');
 await page.locator('[data-test="team-delegated-tasks-header"]').tap();
 await page.locator('[data-test="team-delegated-task-summary-row"]').nth(1).tap();
 await snap('tasks-compact-narrow');
 await page.locator('[data-test="task-direction-team"]').tap();await expectOpen('task-identity-toggle',true);
 await snap('tasks-all-members-narrow');
 await page.locator('[data-test="locale"]').tap();
 await snap('tasks-all-members-zh-narrow');
 await page.locator('[data-test="task-team"]').tap();
 await expectOpen('task-identity-toggle',false);
 await snap('settled-task-participant-narrow');
 await page.setViewportSize({width:1440,height:900});
 await page.locator('[data-test="narrow-panel"]').click();
 await snap('settled-participant-zh-desktop');
 await page.locator('[data-test="mounted"]').click();
 await snap('mounted-team-participant-zh-desktop');
 await page.locator('[data-test="task-identity-toggle"]').click();
 assert.match(await page.locator('[data-test="task-identity-detail"]').innerText(),/mounted-task-worker/);
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-test="narrow-panel"]').click();
 await snap('mounted-team-participant-zh-narrow');
 await page.setViewportSize({width:1440,height:900});
 await page.locator('[data-test="standalone"]').click();
 await snap('standalone-team-tasks-zh-desktop');
 await page.locator('[data-test="task-identity-toggle"]').click();
 assert.match(await page.locator('[data-test="task-identity-detail"]').innerText(),/standalone-task-worker/);
 await page.setViewportSize({width:390,height:844});await snap('standalone-team-task-detail-zh-narrow');
 await page.locator('[data-test="collaboration-messages-header"]').tap();
 await expectOpen('message-identity-toggle',false);await snap('standalone-team-messages-zh-narrow');
 await page.locator('[data-test="message-identity-toggle"]').tap();
 assert.match(await page.locator('[data-test="message-identity-detail"]').innerText(),/standalone-task-worker/);
 await snap('standalone-team-message-detail-zh-narrow');
 evidence.assertions.push('Exact ORG heading; no top strip; compact default; keyboard Enter/Space disclosures; touch controls; all exact settled Team members; reversed submission; references remain distinct; root subject resets; desktop/narrow no page overflow.');
}catch(e){evidence.errors.push(String(e));await snap('failure');process.exitCode=1}
finally{await fs.writeFile('/tmp/aorg-ir040-render/evidence.json',JSON.stringify(evidence,null,2));await browser.close()}
