import { createRequire } from 'node:module'; import fs from 'node:fs/promises'; import path from 'node:path';
const repository='/home/autobyteus/workspace/.codex/worktrees/flat-agent-organization-model';
const require=createRequire(repository+'/autobyteus-server-ts/package.json');
const fastify=require('fastify'), multipart=require('@fastify/multipart'), cors=require('@fastify/cors'), ts=require('typescript');
const {appConfigProvider}=await import(repository+'/autobyteus-server-ts/dist/config/app-config-provider.js');
const {registerContextFileRoutes}=await import(repository+'/autobyteus-server-ts/dist/api/rest/context-files.js');
const {validateAgentOrgRunExecutionTreePayload}=await import(repository+'/autobyteus-server-ts/dist/run-history/store/agent-org-run-execution-tree-schema.js');
const appData=await fs.mkdtemp('/tmp/aorg-ir050-render-data-');
appConfigProvider.config.getAppDataDir=()=>appData;
appConfigProvider.config.getMemoryDir=()=>path.join(appData,'memory');
appConfigProvider.config.getBaseUrl=()=> 'http://127.0.0.1:43151';
const fixture=ts.transpileModule(await fs.readFile(repository+'/autobyteus-web/services/agentOrgExecution/__tests__/taskBearingOrgFixture.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {taskBearingView}=await import(`data:text/javascript;base64,${Buffer.from(fixture).toString('base64')}`);
const tree=validateAgentOrgRunExecutionTreePayload(taskBearingView().execution_tree,'org-run');
const dir=path.join(appData,'memory','agent_orgs','org-run');await fs.mkdir(dir,{recursive:true});
await fs.writeFile(path.join(dir,'agent_org_run_execution_tree.json'),JSON.stringify(tree));
const app=fastify();await app.register(cors,{origin:true});await app.register(multipart);await app.register(registerContextFileRoutes,{prefix:'/rest'});
app.addHook('onResponse',async (request,reply)=>{console.log(JSON.stringify({method:request.method,url:request.url,status:reply.statusCode}));});
await app.listen({port:43151,host:'127.0.0.1'});await fs.writeFile('/tmp/aorg-ir050-render/server-data-root.txt',appData);console.log('READY');
const close=async()=>{await app.close();process.exit(0);};process.on('SIGINT',close);process.on('SIGTERM',close);
