export enum AgentMemberRefScope {
  SHARED = "SHARED",
  TEAM_LOCAL = "TEAM_LOCAL",
  APPLICATION_OWNED = "APPLICATION_OWNED",
}

export enum AgentTeamDefinitionOwnershipScope {
  SHARED = "SHARED",
  TEAM_LOCAL = "TEAM_LOCAL",
  AGENT_ORG_OWNED = "AGENT_ORG_OWNED",
  APPLICATION_OWNED = "APPLICATION_OWNED",
}
