import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire('/home/autobyteus/workspace/.codex/worktrees/flat-agent-organization-model/autobyteus-web/package.json');
const {chromium}=require('playwright-core');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox'],headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});
const evidence={states:[],errors:[],assertions:[],limits:'Implementation-only isolated production history collection with synthetic strict tree and local state; Teams sibling is fixture chrome. No provider, stream, full app route, native or API/E2E signoff.'};
page.on('pageerror',e=>evidence.errors.push(String(e)));
await page.route('**/graphql',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:{agentDefinitions:[],runtimeCapabilities:[],agentTeams:[]}})}));
const heading=page.locator('[data-test="workspace-agent-orgs"] > div.uppercase');
const rows=page.locator('[data-test="render-history"] [role="treeitem"]');
const snap=async(name)=>{
 await page.screenshot({path:`/tmp/aorg-ir041-render/${name}.png`,fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 assert.equal(overflow,false);
 evidence.states.push({name,heading:await heading.innerText(),body:await page.locator('[data-test="render-history"]').innerText(),overflow});
};
try {
 await page.goto('http://127.0.0.1:43141/ir041-heading-render',{waitUntil:'networkidle',timeout:120000});
 await heading.waitFor();
 assert.equal(await heading.innerText(),'ORGS');
 assert.equal(await heading.textContent().then(s=>s.trim()),'Orgs');
 const teams=await page.locator('[data-test="teams-heading"]').boundingBox();
 const orgs=await heading.boundingBox();
 assert.ok(orgs.y>teams.y);
 const before=await rows.evaluateAll(es=>es.map(e=>({id:e.getAttribute('data-test'),selected:e.getAttribute('aria-selected')})));
 await rows.evaluateAll(es=>es.forEach(e=>e.dataset.ir041Identity='retained'));
 await snap('en-desktop');
 await page.locator('[data-test="locale"]').focus(); await page.keyboard.press('Enter');
 await page.waitForFunction(()=>document.querySelector('[data-test="workspace-agent-orgs"] > div.uppercase').textContent.trim()==='组织');
 await snap('zh-desktop');
 await page.setViewportSize({width:390,height:844});
 await snap('zh-narrow');
 await page.locator('[data-test="locale"]').tap();
 await page.waitForFunction(()=>document.querySelector('[data-test="workspace-agent-orgs"] > div.uppercase').textContent.trim()==='Orgs');
 assert.equal(await heading.innerText(),'ORGS');
 await snap('en-narrow');
 assert.deepEqual(await rows.evaluateAll(es=>es.map(e=>({id:e.getAttribute('data-test'),selected:e.getAttribute('aria-selected')}))),before);
 assert.ok(await rows.evaluateAll(es=>es.every(e=>e.dataset.ir041Identity==='retained')));
 const definition=page.locator('[data-test="workspace-agent-orgs"] > div.rounded-md > button');
 await definition.focus(); await page.keyboard.press('Space');
 assert.equal(await definition.getAttribute('aria-expanded'),'false');
 assert.equal(await rows.count(),0);
 await definition.tap();
 assert.equal(await definition.getAttribute('aria-expanded'),'true');
 assert.equal(await rows.count(),before.length);
 evidence.assertions=['English Orgs renders ORGS below Teams','Chinese 组织 unchanged','Locale switches preserve exact row elements, selection and expanded tree','Keyboard Space and touch retain existing disclosure behavior','No desktop/narrow horizontal overflow'];
 assert.deepEqual(evidence.errors,[]);
} finally {await fs.writeFile('/tmp/aorg-ir041-render/evidence.json',JSON.stringify(evidence,null,2));await browser.close();}
console.log(JSON.stringify(evidence,null,2));
